# Generated by Django 5.1 on 2024-09-16 09:19

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('video', models.FileField(upload_to='Advertising/%Y/%m/%d', verbose_name='تبلیغ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ تمدید ')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('note', models.TextField(verbose_name='متن')),
                ('likes', models.IntegerField(default=0, verbose_name='لایک ها ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': 'یادداشت',
                'verbose_name_plural': 'یادداشت ها',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='media', verbose_name='تصویر1')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='media', verbose_name='تصویر2')),
                ('image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='media', verbose_name='تصویر3')),
                ('image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='media', verbose_name='تصویر4')),
                ('image5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='media', verbose_name='تصویر5')),
                ('content', models.TextField(verbose_name='متن تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')),
            ],
            options={
                'verbose_name': 'تصویری ',
                'verbose_name_plural': 'تصویری ها',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='media', verbose_name='تصویر1')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='media', verbose_name='تصویر 2')),
            ],
        ),
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='ارسال کننده')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان ')),
                ('video', models.FileField(blank=True, null=True, upload_to='Submitted', verbose_name='ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('image', models.ImageField(upload_to='Submitted', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'گفت گو',
                'verbose_name_plural': 'گفت گو ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها ',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='blog_catego_name_cb8828_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('full_content', models.TextField(verbose_name='محتوا کامل ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='media', verbose_name='تصویر')),
                ('hot', models.BooleanField(default=False, verbose_name='تیتر خبر ها ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت ')),
                ('video', models.FileField(upload_to='media', verbose_name='فیلم')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='media', verbose_name='تصویر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.category', verbose_name='دسته بندی ')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='کامنت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.photo', verbose_name='تصویری')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
